### ISSUE TITLE
npm run demo failing

### ISSUE THREAD

**Issue by jpdevries** [web-perf/react-worker-dom#20]
```
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config test/webpack.config.js
```

<details>
  <summary>Terminal Output</summary>
<pre>
j15:react-worker-dom jP$ node --version
v6.3.1
j15:react-worker-dom jP$ npm run demo

> react-worker-dom@0.0.1 demo /Users/jP/Sites/node/react-worker-dom
> webpack-dev-server --config test/webpack.config.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:84:10)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "run" "demo"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! react-worker-dom@0.0.1 demo: `webpack-dev-server --config test/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-worker-dom@0.0.1 demo script 'webpack-dev-server --config test/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-worker-dom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config test/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-worker-dom
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-worker-dom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jP/Sites/node/react-worker-dom/npm-debug.log
j15:react-worker-dom jP$ 
</pre>
</details>

<details>
  <summary>NPM Debug Log</summary>
  <pre>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'demo' ]
2 info using npm@3.10.6
3 info using node@v6.3.1
4 verbose run-script [ 'predemo', 'demo', 'postdemo' ]
5 info lifecycle react-worker-dom@0.0.1~predemo: react-worker-dom@0.0.1
6 silly lifecycle react-worker-dom@0.0.1~predemo: no script for predemo, continuing
7 info lifecycle react-worker-dom@0.0.1~demo: react-worker-dom@0.0.1
8 verbose lifecycle react-worker-dom@0.0.1~demo: unsafe-perm in lifecycle true
9 verbose lifecycle react-worker-dom@0.0.1~demo: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/jP/Sites/node/react-worker-dom/node_modules/.bin:/usr/local/Cellar/node/6.3.1/bin:/Users/jP/.rbenv/shims:/Users/jP/.node/bin:/Users/jP/Sites/modx/Gitify:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin:/Users/jP/bin:/usr/local/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin:/opt/X11/bin
10 verbose lifecycle react-worker-dom@0.0.1~demo: CWD: /Users/jP/Sites/node/react-worker-dom
11 silly lifecycle react-worker-dom@0.0.1~demo: Args: [ '-c', 'webpack-dev-server --config test/webpack.config.js' ]
12 silly lifecycle react-worker-dom@0.0.1~demo: Returned: code: 1  signal: null
13 info lifecycle react-worker-dom@0.0.1~demo: Failed to exec demo script
14 verbose stack Error: react-worker-dom@0.0.1 demo: `webpack-dev-server --config test/webpack.config.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid react-worker-dom@0.0.1
16 verbose cwd /Users/jP/Sites/node/react-worker-dom
17 error Darwin 16.5.0
18 error argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "run" "demo"
19 error node v6.3.1
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error react-worker-dom@0.0.1 demo: `webpack-dev-server --config test/webpack.config.js`
22 error Exit status 1
23 error Failed at the react-worker-dom@0.0.1 demo script 'webpack-dev-server --config test/webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-worker-dom package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --config test/webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-worker-dom
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-worker-dom
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
  </pre>
</details>

**Comment by jpdevries** [comment]
My bad. It was because I had nginx running on 8080. Might be nice to have a way to configure the port it runs on?
